### ISSUE TITLE
Add Table of Contents to README

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/headx#10]
### Description:
Currently, the README file lacks a table of contents, which can make it challenging for users and contributors to quickly navigate and find relevant information. Adding a table of contents would improve the documentation's usability and accessibility.

### Proposed Changes:
- Add a table of contents to the README file.
- Organize the table of contents to provide an overview of the document's sections and subsections.
- Ensure that links in the table of contents are properly formatted and lead to the corresponding sections within the document.

### Acceptance Criteria:
- The README file should include a well-structured table of contents.
- Each item in the table of contents should link to the appropriate section within the README.
- The table of contents should be kept up-to-date as the document evolves.

### Additional Information:
- If there are any specific guidelines or preferences for the table of contents format or styling, please specify them here.
- If you need assistance or have any questions while working on this issue, feel free to ask for help in the comments.

**Comment by Pasqua101** [comment]
Hi, would I be able to work on making the table of contents? If no one has started it already.

**Comment by theritikchoure** [comment]
@Pasqua101 yes you can start working on it.

Make changes and raise a Pull Request.

If you like this package and repo, please give a ⭐ star.

Happy Coding 💚!!

**Comment by Pasqua101** [comment]
Thanks! I'll start working on it and I'll let you know if I have any questions.

**Comment by theritikchoure** [comment]
@Pasqua101, Thanks for your contribution.

If you like this package and repo, please give a ⭐ star.

Happy Coding 💚!!
