### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/headx#3]
Add CODE_OF_CONDUCT.md file

**Comment by Radiosnack** [comment]
do you want code of conduct for hacktoberfest ?

**Comment by theritikchoure** [comment]
yes

**Comment by Radiosnack** [comment]
Is there any contact method that i can provide in code of conduct ?

**Comment by theritikchoure** [comment]
Fixes #6
