### ISSUE TITLE
Add relevant badges in readme file

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/headx#4]
Add badges like -

- twitter follow badge
- installation size

And other relevant badges

![image](https://user-images.githubusercontent.com/56495602/198617684-aab0348e-77a7-4fb1-b05b-d3f9191f0ed5.png)

**Comment by Radiosnack** [comment]
hey ! do you mean meta data bagdes ?

**Comment by theritikchoure** [comment]
yes

**Comment by KodcuAhmet** [comment]
Hi 
Can you assign me this, pls? And is your twitter account @theritikchoure the link to be followed by the way?

**Comment by theritikchoure** [comment]
> Hi Can you assign me this, pls? And is your twitter account @theritikchoure the link to be followed by the way?

Yes, @theritikchoure this is my twitter handle, and I assigned this to you.  

@ahmet-cigil

**Comment by theritikchoure** [comment]
#9 Pull request
